services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      TZ: "Australia/Sydney"
      WEBPASSWORD: "kkagnOM101"
      DNS1: "1.1.1.1"
      DNS2: "9.9.9.9"
      ServerIP: "192.168.20.19"
      DNSMASQ_LISTENING: "all"
    volumes:
      - "./etc-pihole/:/etc/pihole/"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
    cap_add:
      - NET_ADMIN
